### ISSUE TITLE
Fix issue on Newsfeed

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/WebApp#165]
We have an issue on the newsfeed where reloading the page on it causes some errors.

**Comment by visualjerk** [comment]
We have a vue hydration issue here, because of ssr dom and clientside dom elements not matching. However it is hard to find out which elements are mismatching.

Components inside comments may cause this type of problem: https://github.com/vuejs/vue/issues/3844

With the commented components inside NewsfeedSort.vue removed the bug seems to be fixed: #169 

However it might still be possible, that contribution content caused this bug and it is now gone, because the problematic content is no more in the initially loaded contributions.

We should keep an eye on this.
