### ISSUE TITLE
"Contribution draft confirmation" bug

### ISSUE THREAD

**Issue by Lulalaby** [Human-Connection/WebApp#333]
Fix #311 

Issue with the draft confirmation.
On edit but with abort of a comment or post, it appears a load later.

![grafik](https://user-images.githubusercontent.com/14029133/47343536-9525d580-d6a6-11e8-8f3b-e65f85d4a3ec.png)

**Comment by Lulalaby** [comment]
@ionphractal

**Comment by Lulalaby** [comment]
Is already known in the team.
For questions either contact @AndreasAusKiel or us.

**Comment by ionphractal** [comment]
The issue arises because beforeRouteLeave is called twice. Seems like this came in with https://github.com/Human-Connection/WebApp/commit/9502320fa4598a6893ad335fd11ca74191eb6b3e or to be precise this line: https://github.com/Human-Connection/WebApp/blob/9502320fa4598a6893ad335fd11ca74191eb6b3e/components/layout/Topbar.vue#L108
When you comment it out, it only triggers once again. But I don't know if this line is required for something else.

@roschaefer Would you please explain me why this was added?
