### ISSUE TITLE
Video Embedding Error / No Other Content

### ISSUE THREAD

**Issue by chrisSCM** [Human-Connection/WebApp#40]
Error: contributions validation failed: contentExcerpt: Path `contentExcerpt` is required.

- excerpt hook API!
- otag scrubber?
- automatically add title photo and excerpt

**Comment by appinteractive** [comment]
I have already added an automatic tagging of video posts plus adding the video preview image as thease image (of not already set).

Some times there is an issue where it can't get the image from youtube. We have to catch them and leave it empty or find the reason why this happens.

For link scrubbing I have added "got" and "metascraper". It works already but we have to marry it with the editor.

For some reason I cant get the ecerpt thingy working when there is only a video. We might make the excerpt optional instead of required.

**Comment by appinteractive** [comment]
The content length is counted without html tags, thats why we get issues here.

**Comment by visualjerk** [comment]
Is this error still reproducible with the new url embeds?

**Comment by appinteractive** [comment]
@chrisSCM still having that issue?
